### ISSUE TITLE
Humidity rounding error

### ISSUE THREAD

**Issue by bekelly** [aemacleod/eight-frame#2]
The humidity complication on my watch is currently showing "57.9999" -- maybe this should be rounded to the nearest whole percent?

**Comment by aemacleod** [comment]
I have noticed that, too. The JSON object comes in from Dark Sky as a decimal between 0.0 to 1.0, and then the JavaScript multiplies that by 100. I'm not sure where the rounding comes in, but I'll take a look. I'm guessing that using Math.round() on the result will fix this.

**Comment by aemacleod** [comment]
I updated it to use Math.round on the line in question. I've been using it for a day or so now and haven't seen the repeating 9's come up again, but if you see it again, let me know.
